version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: javajestsuper
      MYSQL_DATABASE: courseApp
      MYSQL_USER: root
      MYSQL_PASSWORD: javajestsuper
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    image: course-app-image:latest
    ports:
      - "8081:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/courseApp
    depends_on:
      - mysql

volumes:
  db_data:



